version: '3'

services:

  python:
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: Dockerfile.python
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    command: python scrapper.py

  nodejs:
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: Dockerfile.nodejs
    ports:
      - "3333:3333"
    volumes:
      - .:/app
    command: node index.js

