name: Test and Lint

on:
  push:
    branches:
      - 'main'

jobs:

  test-flutter-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
          flutter_version: '2.10.0'

      - name: Test Flutter build
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
          flutter_version: '2.10.0'
          flutter_root: 'client'


  Repository_Mirroring:
    runs-on: ubuntu-latest
    needs:
        - test-flutter-build
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@github.com:aimericdrk/survivor.git
          ssh_private_key:
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}
